5228 create control panel to communicate with each environments external api
The-Digital-Collective/WV.FeatureSwitch.Dashboard.Web pull request #4
Opened 2021-02-14 14:46 UTC by zakiahmed-worldvision

2021-02-16 18:11 UTC, geethakrishnamoorthy commented on WV.FeatureSwitch.Dashboard.Web/Controllers/FeatureSwitchController.cs
> +        public async Task<ActionResult> Update(bool flag, string inputFeatureNames)
- When I look at the MVC Page, We can able to update the N number of records based on the country sites and selected records.
- But in code, it seems to be a general update for all records in all country sites even though if we have selected records. 
- It's totally messy. You have to revamp this code completely for the update, reset, and all the methods.
- Before making the development code, draft the pseudo-code first and get the confirmation from your seniors and then write the code.

2021-02-17 13:53 UTC, zakiahmed-worldvision commented on WV.FeatureSwitch.Dashboard.Web/Controllers/FeatureSwitchController.cs
> +        public async Task<ActionResult> Update(bool flag, string inputFeatureNames)
Yes thats right, it is a global update. A separate story - 5620 has been created to address this comment.

2021-02-17 13:58 UTC, zakiahmed-worldvision commented on WV.FeatureSwitch.Dashboard.Web/Controllers/FeatureSwitchController.cs
> +        public async Task<ActionResult> Update(bool flag, string inputFeatureNames)
All other methods were code reviewed for story - 5229

2021-02-19 18:05 UTC, geethakrishnamoorthy requested changes
1) No Need for the project called BAL and DAL.
2) Move APIClient, Helper, Model, and APIClientFactory folder in WV.FeatureSwitch.Dashboard.Web project.
3) You did not configure serilog in your project, then how you logged your errors? Check the WVUnited4Admin application project.
4) Remove unnecessary files and Menu from project.
5) you no need to create Serilog.cs file. You can call directly serilog logger in your controller methods.. 
6) In FeatureSwitchServiceApiUrls.cs file, Should rename 'eventApiServicePrefix' as appropriate name 
7) Remove helperurls.cs file.
8) You should have negative cases for Getallfeaturemethods in FeatureSwitchControllerTest file.

2021-02-23 10:56 UTC, zakiahmed-worldvision commented on WV.FeatureSwitch.Dashboard.Web/Controllers/FeatureSwitchController.cs
> +            _featureSwitchViewModelList = testFeatureModelList.ToList();
All of these comments will be addressed in the new story "5715 - Rework for Story 5228"

2021-02-23 11:27 UTC, merged

2021-02-23 11:28 UTC, geethakrishnamoorthy commented
I have merged the branch 5228 changes into develop. My feedback points will be addressed in another new story #5716